# Streamlit Secrets 配置模板
# 本地开发时复制这份文件为 .streamlit/secrets.toml
# 云端部署时在 Streamlit Cloud 的 Settings → Secrets 中配置

[华东2]
account_id = "C_P413uOSa-gHpYL7bZWqQ"
client_id = "0Glld9sKR7CYEm8nPkiAUA"
client_secret = "YxNwFsceOJ8g4j0J5JRS1pV2D3zsnnIq"

[华东1]
account_id = "5OV390ryTYyeIwzV1qigbQ"
client_id = "BBTEMJPkQJmcr3PuZ9VoCg"
client_secret = "XoDpIP5hAMNlMKNBV6Wk9g8rulJ9hbbX"

[华东3]
account_id = "sRceTGFlRvC18IO5O3aOtA"
client_id = "MGDCLY0iQ3mlFeNj3BMQTw"
client_secret = "SDAVsK1xju6Jsr9dhtKbr2QxOuQBTKux"

[华东4]
account_id = "5OV390ryTYyeIwzV1qigbQ"
client_id = "TeFXKTPpRyO9MyRdsFZjMA"
client_secret = "z4q945jhLcp8qyJz7mRNttzFG0BpZqFI"
